# SAE Alternants S3
:toc:
:toc-title: Sommaire

<<<

= 1. Équipe

== Étudiant.e.s

- https://github.com/Fiujy[KERROUCHE Mohamed] Développeur
- https://github.com/GalateeM[MARCQ Galatée] SCRUM Master
- https://github.com/LeilaMartinet[MARTINET Leila] Product Owner
- https://github.com/caerroff[MASIN Thomas] Développeur
- https://github.com/hugomonte[MONTE Hugo] Développeur

== Professeur.e.s
- https://github.com/rboulle[Rémi Boulle]
- https://github.com/ependaries[Esther Pendaries]

= 2. Contexte du projet

La SAE 3.01 est une SAE inter-départements, réalisée en collaboration entre les étudiants de seconde année de BUT Génie Industriel et Maintenance et nous-mêmes, étudiants en deuxième années de BUT Informatique. Ces derniers ayant amélioré une tireuse à bière en lui intégrant des capteurs, ils ont besoin que nous leur développions une application permettant d’exploiter graphiquement les données ainsi récupérées, afin de gérer l’état et les pannes éventuelles de la machine.

= 3. Livrables

|=============
| Date | Nom du livrable | Lien vers le livrable 
| | Documentation Technique | https://github.com/GalateeM/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-5/blob/main/Documentation/DocumentationTechnique.adoc[Dossier d'analyse et de conception]
| | Documentation Utilisateur | https://github.com/GalateeM/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-5/blob/main/Documentation/DocumentationUtilisateur.adoc[Documentation utilisateur]
| | Cahier des tests | https://github.com/GalateeM/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-5/blob/main/Documentation/CahierTests.adoc[Cahier des tests]
|=============

= 4. Gestion du projet 


Liste des US en cours https://github.com/GalateeM/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-5/issues[ici] +
Version courante du projet V1.0

Backlog produit : https://github.com/GalateeM/SAE-ALT-S3-Dev-22-23-STDS-3B-Equipe-5/blob/main/Documentation/Gestion%20de%20projet/BacklogProduit.adoc[ici]

Backlog sprint :

- Sprint 1 : https://www.github.com/users/GalateeM/projects/3[ici] +
- Sprint 2 : https://www.github.com/users/GalateeM/projects/4[ici]


= 5. Méthode SCRUM
- Retour d'expérience sprint 1 : +

Durant ce premier sprint, nous avons mis en place le projet sur Github. Nous avons également réalisé les fonctionnalités `En tant qu'utilisateur je souhaite consulter les données de la tireuse en temps réel` et `Mise en place de l'infrastructure d'accès aux données`. Concernant la fonctionnalité `En tant qu'utilisateur je souhaite pouvoir consulter l'historique des données de la tireuse sur une période donnée`, nous avions commencé par la réaliser en partie avec Node-RED et l'autre partie avec NodeJS, mais finalement nous avons vu que nous pouvions tout faire en NodeJS donc nous avons perdu un peu de temps. Cette fonctionnalité est toujours en cours de réalisation, mais elle est pratiquement terminée. +
Les fonctionnalités `En tant qu'utilisateur, je souhaite pouvoir accéder à une page contenant les pannes actuelles afin de pouvoir les corriger` et `En tant qu'utilisateur je souhaite être notifié lorsqu'une panne survient et connaître le type précis de la panne` viennent d'être commencées, et elles étaients prévues pour le sprint 2. +
Nous sommes donc dans les temps pour terminer le projet, mais n'avons quasiment pas de marge pour du retard. +

Concernant les difficultés, les technologies utilisées étaient nouvelles pour la majorité des membres de l'équipe, il fallait donc arriver à s'auto-former. Malgré ces difficultés, nous avons réussi nos premières fonctionnalités.


=== retour sprint semaine 3

Documentations ok 
Tests ok (pourquoi version 3 ?)

Backlog produit :  attention il manque la finalité de vos US (afin de ...). Les US sont mal créées sous Github je n'ai pas le label US et les tâches liées entre autre. Revoir la vidéo.

Backlog sprint :  votre lien ne marche pas ... je ne trouve pas votre srintboard 3 et le futur sprintboard 4.

CR ok ... bon courage ... j'espère avoir une release à la fin de la semaine car rien à la fin du sprint 3 ... 


- Retour d'expérience sprint 2 : +

TO DO
