version: "3"

services:
  nodered:
    image: nodered/node-red:3.0.2
    ports:
      - 8080:1880

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=timescale
      - POSTGRES_PASSWORD=password

  back:
    depends_on:
        - timescaledb
    build:
      context: .
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - MQTT_URL=mqtt://iot.iut-blagnac.fr:1883
      - MQTT_USERNAME=student
      - MQTT_PASSWORD=student